library(readr)
marks <- read_csv("marks.csv")
View(marks)
cor(marks$`English (mark)`,marks$`Maths (mark)`)
cor(marks$`English (mark)`,marks$`Maths (mark)`,method="spearman")
hist(marks$`English (mark)`)
hist(marks$`Maths (mark)`)
plot(marks$`English (mark)`,marks$`Maths (mark)`)
abline(lm(marks$`Maths (mark)`~marks$`English (mark)`))
